name: Test Project Card Move

on:
  project_card:
    types: [moved]

jobs:
  test_trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Log Trigger Event
        run: echo "Project card moved!"
        